name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install pip and uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r pyproject.toml

      - name: Run linter
        run: uv run make lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install pip and uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r pyproject.toml

      - name: Create .env file
        run: |
          cd fastqueue
          echo "DJANGO_SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          cd ..

      - name: Run tests
        run: uv run make test